### ISSUE TITLE
KeyError: 'G_latent_L1loss_val' when train step2

### ISSUE THREAD

**Issue by batman47steam** [ruixv/NLOS-OT#3]
你好，在训练完step2的一个epoch以后，val的过程中`errors = model.get_current_errors_val()` 实际上是返回一个只有两个key的字典，key分别是`G_otlatent_val`和`G_Content_val`但是在下面会用`G_latent_L1loss_val`这个key对errors字典进行索引，从而产生key error的错误
![image](https://github.com/ruixv/NLOS-OT/assets/36287035/f2185e7c-7a59-493d-af5d-fcfc413155bd)

step2的train.py中，73-76行
- `get_current_errors_val` 返回的字典
![image](https://github.com/ruixv/NLOS-OT/assets/36287035/bbf54dd1-d9c0-49c7-9c48-15616ff1d05f)
- `errors['G_latent_L1loss_val‘] `用不存在的key对error字典进行索引
![image](https://github.com/ruixv/NLOS-OT/assets/36287035/5370d808-30f8-4055-87da-b4e4996e6e1f)

**Comment by batman47steam** [comment]
您好，还有一些其他的问题想进一步的交流一下，但是个人注意的邮箱好像无法接受邮件

**Comment by ruixv** [comment]
感谢提醒，已修复
